### ISSUE TITLE
Cod Maya Tools

### ISSUE THREAD

**Issue by swizzybeatz** [dtzxporter/ModmeForums#1]
does cod maya tools not work anymore? every version i download doesn’t work. i try to load it in maya and it legit just doesn’t let me click load. i don’t get any errors or anything. Maybe it’s something to do with something on my computer? I don’t know i’m not sure but any help would be greatly appreciated. im trying to port from older cods

**Comment by dtzxporter** [comment]
Unfortunately modme doesn't maintain this plugin. You'll have to find the author.
